config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  root to: 'pages#index'
  resources :committees, only: [] do
    resource :client, only: [:update] do
      get :index , to: 'clients#index'
    end
    resources :admin, only: [:index, :create, :new]
  end
  resources :sessions, only: [:new, :create, :destroy]
  get '/log_in', to: 'sessions#new'
  delete '/log_out', to: 'sessions#destroy'
end

app/models/committee.rb
class Committee < ActiveRecord::Base
  has_many :delegates
  has_many :users
end

app/models/delegate.rb
class Delegate < ActiveRecord::Base
  belongs_to :committee
  default_scope { order('country ASC') }
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  belongs_to :committee

  def is_admin?
    return self.is_admin
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_login
  def index
    @committee_name = Committee.find(params[:committee_id]).name
    unless current_user.is_admin?
      unless params[:committee_id].to_i == current_user.committee_id
        flash[:warning] = 'You cannot access this Committee'
        redirect_to root_path
      end
    end
  end

  def new
  end

  def create
    committee_id = params[:committee_id].to_i
    country = params[:country]
    Delegate.create(country: country, committee_id: committee_id) unless Delegate.find_by(country: country, committee_id: committee_id)
    redirect_to root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def not_authenticated
    flash[:warning] = 'You need to login to access this page'
    redirect_to log_in_path
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :require_login
  include ClientHelper
  def index
    @committee_name = Committee.find(params[:committee_id]).name
    # unless current_user.is_admin?
    #   unless params[:committee_id].to_i == current_user.committee_id
    #     flash[:warning] = 'You cannot access this Committee'
    #     redirect_to root_path
    #   end
    # end
    if params[:committee_id].to_i != current_user.committee_id && current_user.is_admin? == false
      flash[:warning] = 'You cannot access this Committee'
      redirect_to root_path
    end


  end

  def update
    delegate_id = params[:delegate_id].to_i
    # puts delegate_id
    committee_id = params[:committee_id].to_i
    # puts committee_id
    score = params[:score].to_i
    # puts score
    @identifier = params[:identifier].to_s
    # puts @identifier

    if @identifier == 'l'
      if score == 1
        score = true
      elsif score == 0
        score = false
      end
    end
    fields = update_identifier(@identifier)
    delegate = Delegate.find_by(id: delegate_id, committee_id: committee_id)
    if @identifier != 'l' && delegate.send("#{fields[0]}").to_i > 0
      delegate.send("#{fields[1]}=", (delegate.send("#{fields[1]}")).to_i + 1) unless fields[1] == ''
    end
    delegate.send("#{fields[0]}=", score)
    delegate.save

    respond_to do |format|
      format.js {}
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if login(params[:username], params[:password])
      if current_user.is_admin?
        flash[:success] = "Welcome back, Admin !"
        redirect_back_or_to root_path
      else
        flash[:success] = "Welcome back, Chair of #{current_user.committee.name.upcase} !"
        redirect_back_or_to committee_client_path(committee_id: current_user.committee_id.to_i)
      end


    else
      flash.now[:warning] = 'Username and/or password is incorrect'
      render 'new'
    end
  end

  def destroy
    logout
    flash[:success] = 'See you !'
    redirect_to log_in_path
  end
end

app/helpers/admin_helper.rb
module AdminHelper
  def score(id)
    delegates = Committee.find(id).delegates
    scores = []
    delegates.each do |delegate|
      speaker_list = (delegate.speaker_list_score.to_f / delegate.speaker_list_count.to_f).round(1)
      poi = (delegate.poi_score.to_f / delegate.poi_count.to_f).round(1)
      ror = (delegate.ror_score.to_f / delegate.ror_count.to_f).round(1)
      ros = (delegate.ros_score.to_f / delegate.ros_count.to_f).round(1)
      mod_structure = (delegate.mod_structure_score.to_f / delegate.mod_structure_count.to_f).round(1)
      mod_speech = (delegate.mod_speech_score.to_f / delegate.mod_speech_count.to_f).round(1)
      lobbying = (delegate.lobbying_score.to_f / delegate.lobbying_count.to_f).round(1)
      fps = (delegate.fps.to_f).round(1)
      res_speech = (delegate.res_speech_score.to_f / delegate.res_speech_count.to_f).round(1)
      amendments = (delegate.amendments_score.to_f / delegate.amendments_count.to_f).round(1)
      other_speeches = (delegate.other_speeches_score / delegate.other_speeches_count.to_f).round(1)
      final_score = speaker_list + poi + ror + ros + mod_structure + mod_speech + lobbying + fps + res_speech + amendments + other_speeches
      scores.push([delegate.country, speaker_list, poi, ror, ros, mod_structure, mod_speech, lobbying, fps, res_speech, amendments, other_speeches, final_score, delegate.speaker_list_score , delegate.speaker_list_count , delegate.poi_score , delegate.poi_count , delegate.ror_score , delegate.ror_count , delegate.ros_score , delegate.ros_count , delegate.mod_structure_score , delegate.mod_structure_count , delegate.mod_speech_score , delegate.mod_speech_count , delegate.lobbying_score , delegate.lobbying_count , delegate.res_speech_score , delegate.res_speech_count , delegate.amendments_score , delegate.amendments_count , delegate.other_speeches_score,  delegate.other_speeches_count])
    end
    scores
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_helper.rb
module ClientHelper
  def isSpecial?(id)
    if Committee.find(id).special
      return true
    else
      return false
    end
  end

  def get_country_list(id)
    delegates = Committee.find(id).delegates
    country = {}
    delegates.each do |delegate|
      country[delegate.id] = delegate.country
    end
    country
  end

  def update_identifier(id)
    fields = []

    case id
    when 'a'
      fields[0] = 'speaker_list_score'
      fields[1] = 'speaker_list_count'
    when 'b'
      fields[0] = 'poi_score'
      fields[1] = 'poi_count'
    when 'c'
      fields[0] = 'ror_score'
      fields[1] = 'ror_count'
    when 'd'
      fields[0] = 'ros_score'
      fields[1] = 'ros_count'
    when 'e'
      fields[0] = 'mod_structure_score'
      fields[1] = 'mod_structure_count'
    when 'f'
      fields[0] = 'mod_speech_score'
      fields[1] = 'mod_speech_count'
    when 'g'
      fields[0] = 'lobbying_score'
      fields[1] = 'lobbying_count'
    when 'h'
      fields[0] = 'fps'
      fields[1] = ''
    when 'i'
      fields[0] = 'res_speech_score'
      fields[1] = 'res_speech_count'
    when 'j'
      fields[0] = 'amendments_score'
      fields[1] = 'amendments_count'
    when 'k'
      fields[0] = 'other_speeches_score'
      fields[1] = 'other_speeches_count'
    when 'l'
      fields[0] = 'sponsor'
      fields[1] = ''
    end

    return fields
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_panel_helper.rb
module UserPanelHelper
end

app/views/admin/index.html.haml
.card-panel.blue-grey
  %h1.center.white-text Points System - Admin Panel
  %h2.center.white-text.uppercase #{@committee_name}
  .card-panel.white
    %table.striped.responsive-table.centered
      %thead
        %tr
          %th{"data-field" => "id"} Country
          %th{"data-field" => "id"} Speaker List
          %th{"data-field" => "id"} POI
          %th{"data-field" => "id"} ROR
          %th{"data-field" => "id"} ROS
          %th{"data-field" => "id"} MOD Struc
          %th{"data-field" => "id"} MOD Speech
          %th{"data-field" => "id"} Lobbying
          %th{"data-field" => "id"} FPS
          %th{"data-field" => "id"} Res Speech
          %th{"data-field" => "id"} Amendments
          %th{"data-field" => "id"} Other Speeches
          %th{"data-field" => "name"} Score
      %tbody
        - score(params[:committee_id]).each do |score|
          %tr
            %td #{score[0]}
            %td #{score[1]}
            %td #{score[2]}
            %td #{score[3]}
            %td #{score[4]}
            %td #{score[5]}
            %td #{score[6]}
            %td #{score[7]}
            %td #{score[8]}
            %td #{score[9]}
            %td #{score[10]}
            %td #{score[11]}
            %td #{score[12]}
          %tr
            %td
            %td #{score[13]} | #{score[14]}
            %td #{score[15]} | #{score[16]}
            %td #{score[17]} | #{score[18]}
            %td #{score[19]} | #{score[20]}
            %td #{score[21]} | #{score[22]}
            %td #{score[23]} | #{score[24]}
            %td #{score[25]} | #{score[26]}
            %td
            %td #{score[27]} | #{score[28]}
            %td #{score[29]} | #{score[30]}
            %td #{score[31]} | #{score[32]}
            %td 

app/views/admin/new.html.haml
= form_tag(committee_admin_index_path, :method=>'post') do

   %h5 Commitee
   = text_field_tag "committee"

   %h5 Country
   = text_field_tag "country"

   = submit_tag 'Submit'

app/views/clients/_score_cards.html.haml
.card-panel.blue-grey#score_cards
  %h1.center.white-text Points System - #{@committee_name.upcase}
  -# %select.browser-default.country-select
  -#   %option{:disabled => "", :selected => "", :value => ""} Choose a Country
  -#   - get_country_list(params[:committee_id]).each do |country|
  -#     %option{:value => country[0]} #{country[1]}
  .row
    .col.s12.m6.l3
      .card.z-depth-2
        .card-content.center
          %p.card-title.flow-text Speaker List
          .input-field
            -if isSpecial?(params[:committee_id])
              = render partial: 'clients/score_selection', locals: {max_val: 20, min_val: 1, type: 'a'}
            -else
              = render partial: 'clients/score_selection', locals: {max_val: 10, min_val: 1, type: 'a'}
          %button.waves-effect.waves-light.btn.z-depth-1.update{type: 'a'} Update
    .col.s12.m6.l3
      .card.z-depth-2
        .card-content.center
          %p.card-title.flow-text P.O.I
          .input-field
            = render partial: 'clients/score_selection', locals: {max_val: 5, min_val: 1, type: 'b'}
          %button.waves-effect.waves-light.btn.z-depth-1.update{type: 'b'} Update
    .col.s12.m6.l3
      .card.z-depth-2
        .card-content.center
          %p.card-title.flow-text Right to Reply
          .input-field
            = render partial: 'clients/score_selection', locals: {max_val: 10, min_val: 1, type: 'c'}
          %button.waves-effect.waves-light.btn.z-depth-1.update{type: 'c'} Update
    .col.s12.m6.l3
      .card.z-depth-2
        .card-content.center
          %p.card-title.flow-text R. to a Statement
          .input-field
            = render partial: 'clients/score_selection', locals: {max_val: 5, min_val: 1,type: 'd'}
          %button.waves-effect.waves-light.btn.z-depth-1.update{type: 'd'} Update
    .col.s12.m6.l3
      .card.z-depth-2
        .card-content.center
          %p.card-title.flow-text Mod. C. Struct
          .input-field
            = render partial: 'clients/score_selection', locals: {max_val: 5, min_val: 1,type: 'e'}
          %button.waves-effect.waves-light.btn.z-depth-1.update{type: 'e'} Update
    .col.s12.m6.l3
      .card.z-depth-2
        .card-content.center
          %p.card-title.flow-text Mod. C. Speech
          .input-field
            = render partial: 'clients/score_selection', locals: {max_val: 5, min_val: 1,type: 'f'}
          %button.waves-effect.waves-light.btn.z-depth-1.update{type: 'f'} Update
    .col.s12.m6.l3
      .card.z-depth-2
        .card-content.center
          %p.card-title.flow-text Lobbying
          .input-field
            = render partial: 'clients/score_selection', locals: {max_val: 5, min_val: 1,type: 'g'}
          %button.waves-effect.waves-light.btn.z-depth-1.update{type: 'g'} Update
    .col.s12.m6.l3
      .card.z-depth-2
        .card-content.center
          %p.card-title.flow-text F.P.S
          .input-field
            = render partial: 'clients/score_selection', locals: {max_val: 15, min_val: 1,type: 'h'}
          %button.waves-effect.waves-light.btn.z-depth-1.update{type: 'h'} Update
    .col.s12.m6.l3
      .card.z-depth-2
        .card-content.center
          %p.card-title.flow-text Res. Speeches
          .input-field
            = render partial: 'clients/score_selection', locals: {max_val: 10, min_val: 1,type: 'i'}
          %button.waves-effect.waves-light.btn.z-depth-1.update{type: 'i'} Update
    .col.s12.m6.l3
      .card.z-depth-2
        .card-content.center
          %p.card-title.flow-text Amendments
          .input-field
            = render partial: 'clients/score_selection', locals: {max_val: 5, min_val: 1,type: 'j'}
          %button.waves-effect.waves-light.btn.z-depth-1.update{type: 'j'} Update
    .col.s12.m6.l3
      .card.z-depth-2
        .card-content.center
          %p.card-title.flow-text Other speeches
          .input-field
            = render partial: 'clients/score_selection', locals: {max_val: 10, min_val: 1,type: 'k'}
          %button.waves-effect.waves-light.btn.z-depth-1.update{type: 'k'} Update
    .col.s12.m6.l3
      .card.z-depth-2
        .card-content.center
          %p.card-title.flow-text Is Sponsor ?
          .input-field{identifier: 1}
            = render partial: 'clients/yes_no_selection' , locals: {type: 'l'}
          %button.waves-effect.waves-light.btn.z-depth-1.update{type: 'l'} Update

app/views/clients/_score_selection.html.haml
%input.validate.center.score-enter{:type => "number", :placeholder => " / #{max_val}", max: max_val, min: min_val, id: type}

app/views/clients/_yes_no_selection.html.haml
%select{id: type}
  %option{:selected => "", :value => "0"} No
  %option{:value => "1"} Yes

app/views/clients/index.html.haml
.row
  .col.s2
    .collection.z-depth-2#country_collection{style: 'overflow-y:scroll'}
      - get_country_list(params[:committee_id]).each do |country|
        %a.collection-item{:value => country[0]} #{country[1]}

  .col.s10
    = render 'score_cards'
:coffeescript
  $(document).on "page:change", ->
    score_card_height = $('#score_cards').height()
    $('#country_collection').height(score_card_height)

    $('.collection-item').click ->
      if $(this).hasClass('active')
        $(this).removeClass('active')
      else
        $('.collection-item').removeClass('active')
        $(this).addClass('active')
      return

    $('select').material_select()
    $('.score-enter').change ->
      value = parseInt(@value)
      max = parseInt(@max)
      min = parseInt(@min)
      if value > max
        @value = max
      if value < min
        @value = min
      return
    $('.update').on 'click', ->
      score = $('#' + $(this).attr('type')).val()
      $('#' + $(this).attr('type')).val('')
      if ($('.collection-item.active').attr('value') == undefined)
        Materialize.toast('Please select a country', 2000)
        return
      if (score > 0)
        $(this).addClass('disabled')
        $(this).text('Updating')
        $.ajax
          type: 'PATCH'
          url: '#{committee_client_path}'
          data:
            delegate_id: $('.collection-item.active').attr('value')
            committee_id: #{params[:committee_id]}
            score: score
            identifier: $(this).attr('type')
          dataType: 'script'
      else
        console.log 'Attempted to score with score < 0 or nil'
      return

app/views/clients/update.js.erb
Materialize.toast("Updated " + $('#' + "<%= escape_javascript @identifier %>").parent().siblings("span").text(), 1000,'', function(){
  $('#' + "<%= escape_javascript @identifier %>").val('');
  $("button[type= <%= escape_javascript @identifier %>]").removeClass('disabled');
  $("button[type= <%= escape_javascript @identifier %>]").text('Update');
});

app/views/layouts/_nav_links_for_auth.html.haml
- if user_signed_in?
  %li= link_to 'Edit account', edit_user_registration_path
  %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  %li= link_to 'Sign in', new_user_session_path
  %li= link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title COMUN 2016
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    :javascript
      !function(a,b,c,d,e,f,g,h){a.RaygunObject=e,a[e]=a[e]||function(){
      (a[e].o=a[e].o||[]).push(arguments)},f=b.createElement(c),g=b.getElementsByTagName(c)[0],
      f.async=1,f.src=d,g.parentNode.insertBefore(f,g),h=a.onerror,a.onerror=function(b,c,d,f,g){
      h&&h(b,c,d,f,g),g||(g=new Error(b)),a[e].q=a[e].q||[],a[e].q.push({
      e:g})}}(window,document,"script","//cdn.raygun.io/raygun4js/raygun.min.js","rg4js");

  %body
    %nav.grey.darken-2
      .container
        .nav-wrapper
          %a.brand-logo{:href => root_path } COMUN 2016
          %ul#nav-mobile.right
            %li
              %a.dropdown-button{"data-activates" => "coms", :href => "#"}
                Committees
                %i.material-icons.right arrow_drop_down
            - if current_user
              %li
                = link_to 'Log Out', log_out_path, method: :delete
            - else
              %li
                = link_to 'Log In', log_in_path
        - flash.each do |key, value|
          :javascript
            Materialize.toast("#{value}", 4000)

    %ul#coms.dropdown-content
      %li
        %a{:href => committee_client_path(committee_id: 1)} GA1
      %li
        %a{:href => committee_client_path(committee_id: 2)} GA3
      %li
        %a{:href => committee_client_path(committee_id: 3)} GA4
      %li
        %a{:href => committee_client_path(committee_id: 4)} ECOSOC
      %li
        %a{:href => committee_client_path(committee_id: 5)} SC
      %li
        %a{:href => committee_client_path(committee_id: 6)} UNHCR
      %li
        %a{:href => committee_client_path(committee_id: 7)} UNEP


    .container
      = yield

:javascript
  $(".dropdown-button").dropdown();
  rg4js('apiKey', 'Gycriwm5dY7wo0QrQh/A0Q==');
  rg4js('attach', true);
  rg4js('enablePulse', true);

app/views/pages/index.html.haml
.card-panel.blue-grey
  %h1.center.white-text COMUN 2016 Points System
  .center
    %a.waves-effect.waves-light.btn.white.black-text Stuff